### ISSUE TITLE
tnt blew up and now im being raided by the police

### ISSUE THREAD

**Issue by Rhyguy1** [minMaximilian/maxs-pvp-enhancements#2]
### Describe the Bug

I blew up a tnt in a cave and no Im under arrest for 4 charges of assault.

### Reproduction Steps

1.Commit 4 charges of assault 16 months ago
2. blow up tnt in a cave
3. done!!!1!!
...

### Expected Result

prison ):

### Operating System

Windows of my house are destroyed

### Mod Version

0.0.1

### Minecraft Version

1.19.2

### Other Mods

create mod !!!1!!

**Comment by minMaximilian** [comment]
Issue Closed: Troll Issue
